apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-builder-cronjob
spec:
  schedule: {{ quote .Values.modelBuilder.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: model-builder
    spec:
      activeDeadlineSeconds: 60
      ttlSecondsAfterFinished: 120
      template:
        spec:
          terminationGracePeriodSeconds: 120
          containers:
            - name: model-builder
              image: {{ .Values.modelBuilder.image.repository }}:{{ .Values.modelBuilder.image.tag }}
              imagePullPolicy: Never
          restartPolicy: OnFailure