apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-service
spec:
  replicas: {{ .Values.recommendationsService.replicas }}
  selector:
    matchLabels:
      app: recommendations-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recommendations-service
    spec:
      containers:
        - name: recommendations-service
          image: {{ .Values.recommendationsService.image.repository }}:{{ .Values.recommendationsService.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8000