apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
spec:
  type: NodePort
  selector:
    app: recommendations-service
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000